services:
  c44180c-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: c44180c
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
      TZ: Asia/Tokyo
    ports:
      - 13306:3306
    platform: linux/arm64
    volumes:
      - c44180c-db-data:/var/lib/mysql

volumes:
  c44180c-db-data:
